### PR TITLE
Added Japanese translation of Intro

### PR DESCRIPTION
**Pull request by makotot**
It would be very valuable documentation to learn about Rust, so it would be helpful to be able to read it translated into my native language. Thank you so much.
I added ja in i18n and replaced only ~~overview.md~~ intro.md with the translated text (with the intention of translating each page sequentially in the near future), so I'd be happy to hear feedback.

### CODE REVIEW

**Comment by Boshen** [comment]
You may raise any issues about the English first so can I update it. Some of the materials are slightly outdated (to Oxc), I can update those if you thinkthe current content is not helpful any more.

**Comment by Boshen** [comment]
image

cc @nissy-dev, This may interest you 😁

**Comment by nissy-dev** [comment]
This is awesome! If there is anything I can do to help, please let me know! 

FYI: the following tool will reduce translation cost. Actually it was used when translating official react.dev documentation into Japanese.
gpt translator: https://github.com/smikitky/markdown-gpt-translator

**Comment by makotot** [comment]
@Boshen 
Thanks for taking the time to check! I will report back if I find any problems with the English document.

@nissy-dev 
Thanks for sharing the tools to help with translation! If you find any problems with the Japanese translation, I would appreciate it if you could point them out.

**Pull request merged**
