### PR TITLE
Completed a translation into Japanese 🇯🇵 

### PR DESCRIPTION
**Pull request by ubugeeei**
@Boshen 

I have addressed all parts that were not yet translated into Japanese in both the docs and blog 😄 🇯🇵 

- The baseline was produced using a translation tool powered by a generative AI that I had.
- Based on the above, I adjusted unnatural expressions and terminology.
- For quoted sections, I have left the original text (in English) as is.
- I have verified that URLs and similar elements in the text are valid.

---

Additionally, I noticed something in the original text of the book that caught my attention:

```
Source Text --> Token --> Lexer --> Parser --> AST
```

This was changed to:

```
Source Text --> Lexer --> Token --> Parser --> AST
```

If my understanding is incorrect, I will revert it to the original.

ref: https://oxc-project.github.io/javascript-parser-in-rust/docs/overview

### CODE REVIEW

**Comment by nozomuikuta** [comment]
@Boshen 
If you are busy, I can help reviewing as a native Japanese speaker 🙋‍♂️

**Comment by ubugeeei** [comment]
As you can see from [this issue](https://github.com/oxc-project/javascript-parser-in-rust/issues/15), it seems that Boshen doesn't read Japanese, so while there's a move to just go ahead and integrate it for now, since a Japanese-speaking reviewer has kindly volunteered, it might be better to have him review it first before passing it on to Boshen. 😄 

@NozomuIkuta 

I would greatly appreciate it if you could review it!

**Comment by ubugeeei** [comment]
If we have a reviewer available, it might have been better to release it in smaller portions. If you prefer, I can split the PR 🫠

**Comment by Boshen** [comment]
The power of AI 💪 

I'm just going to merge this, @NozomuIkuta You may PR corrections if AI sounded weird.

@Ubugeeei Thank you so much for the help, I'll correct the `Source Text --> Token --> Lexer --> Parser --> AST` thing myself.

**Pull request merged**
